# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3679fb1cfac525b80408153d71b5f493221e5ee82d32f12d9a6df56acac2b8602c085de3bd90b6935d9c9931ff57cba4d4c2269c916bcc2cb102f9b55d1f5bb

test:
  secret_key_base: a6b2d9b5f543f89b7501232ac6d7ef46ee4686bc4e56b4c218a934e138a7522c705a84cd41ffbe1c4361a6335c2e5ece698e940b2eded537d1efeb4d877219ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
